"""
Django settings for tinymce_demo project.

Generated by 'django-admin startproject' using Django 3.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
import sys
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
sys.path.append(str(BASE_DIR / 'apps'))
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-f&%2vaseww*t)x-m%ysq1a9)3$wj=0jw+a80oht&^!cq)(y$*e'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'tinymce_demo.apps.TinymceConfig',
    'tinymce',
    'rest_framework',
]

MIDDLEWARE = [
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

gettext = lambda s: str(s)
LANGUAGES = (
    ('uz', gettext('Uzbek')),
    ('ru', gettext('Russian')),
    ('en', gettext('English')),
)
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

MEDIA_ROOT = Path(BASE_DIR / 'media')
MEDIA_URL = '/media/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

TINYMCE_DEFAULT_CONFIG = {
    'selector': 'textarea',
    "theme": "silver",
    "height": 500,
    "width": 1000,
    "menubar": True,
    "plugins": "advlist,anchor,autolink,autoresize,lists,link,image,imagetools,charmap,print,preview,anchor,"
               "searchreplace,visualblocks,code,fullscreen,insertdatetime,media,table,"
               "code,help,wordcount,paste",
    'paste_remove_styles': True,
    'paste_data_images': True,
    # 'paste_as_text': True,
    # 'paste_merge_formats': True,

    'images_reuse_filename': True,
    'valid_elements': 'a[href|target|style],link[href|rel|type|media|sizes|style],'
                      'h1[style],h2[style],h3[style],h4[style],h5[style],h6[style],'
                      'p[style],pre[style],div[style],em[style],i[style],b[style],span[style],strong[style],u[style],'
                      'ol[start|style],li[value|style],ul[value|style],'
                      'colspan[style],rowspan[style],'
                      'br[style],hr[style],button[type|name|value|disabled|style],'
                      'blockquote[cite|style],code[style],'
                      'canvas[id|width|height|style],svg[width|height|style],'
                      'option[value|disabled|selected|style],select[name|disabled|multiple|size|style],'
                      'figure[style],iframe[src|width|height|style],img[src|alt|width|height|srcset|sizes|style],'
                      'video[src|poster|autoplay|loop|controls|muted|width|height|style],'
                      'source[src|type|srcset|sizes|media|style],'
                      'audio[src|autoplay|loop|controls|style],track[src|kind|srclang|label|default|style]'
                      'table[style],tbody[style],tr[style],td[colspan|rowspan|style],template[style],'
                      'tfoot[style],th[scope|colspan|rowspan|style],thead[style],',
    "toolbar": "undo redo | formatselect | bold italic backcolor | alignleft aligncenter "
               "alignright alignjustify | bullist numlist outdent indent | removeformat | help",
    "paste_retain_style_properties": "",
    'images_upload_url': '/tinymce_image_upload/',  # the URL where the images will be posted
    'relative_urls': False
}

TINYMCE_FULL_CONFIG = {}
TINYMCE_SIMPLE_CONFIG = {}
TINYMCE_TABLE_CONFIG = {}
