# Generated by Django 4.2.4 on 2023-08-03 12:49

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uz', models.CharField(max_length=255, verbose_name='title_uz')),
                ('description_uz', tinymce.models.HTMLField(max_length=10000, verbose_name='description_uz')),
                ('title_ru', models.CharField(max_length=255, verbose_name='title_ru')),
                ('description_ru', tinymce.models.HTMLField(max_length=10000, verbose_name='description_ru')),
                ('title_en', models.CharField(max_length=255, verbose_name='title_en')),
                ('description_en', tinymce.models.HTMLField(max_length=10000, verbose_name='description_en')),
            ],
        ),
        migrations.CreateModel(
            name='TinyMCEPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original', models.ImageField(max_length=255, upload_to='TinyMCEPicture/original/', verbose_name='original')),
                ('converted', models.ImageField(max_length=255, upload_to='TinyMCEPicture/converted/', verbose_name='converted')),
            ],
        ),
    ]
